[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
liquidity_pool = "4B6SCjBKMUvBzv5epJK7GeVfHGwGZb5EdEVxGbZakb7u"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/tgoky/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
